name: Scan
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.event_name != 'merge_group' && format('{0}-{1}', github.workflow, github.head_ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: block
          allowed-endpoints: >
            9236a389bd48b984df91adc1bc924620.r2.cloudflarestorage.com:443
            api.github.com:443
            apk.cgr.dev:443
            auth.docker.io:443
            cgr.dev:443
            check.trivy.dev:443
            ghcr.io:443
            github.com:443
            kics.io:443
            mirror.gcr.io:443
            oss-fuzz-build-logs.storage.googleapis.com:443
            pkg-containers.githubusercontent.com:443
            production.cloudflare.docker.com:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            semgrep.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  #v6.0.1

      # Run the current PR's scan action
      - name: Scan code
        uses: ./scan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_severity: "high"
